export const GET_NOTES_START = 'GET_NOTES_START';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_FAIL = 'GET_NOTES_FAIL';

export const ADD_NOTE_START = 'ADD_NOTE_START';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL';

export const EDIT_NOTE_START = 'EDIT_NOTE_START';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const EDIT_NOTE_FAIL = 'EDIT_NOTE_FAIL';

export const DELETE_NOTE_START = 'DELETE_NOTE_START';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAIL = 'DELETE_NOTE_FAIL';

export const SET_SELECTED_NOTE_START = 'SET_SELECTED_NOTE_START';
export const SET_SELECTED_NOTE_SUCCESS = 'SET_SELECTED_NOTE_SUCCESS';
export const SET_SELECTED_NOTE_FAIL = 'SET_SELECTED_NOTE_FAIL';

export const GET_SELECTED_NOTE_START = 'GET_SELECTED_NOTE_START';
export const GET_SELECTED_NOTE_SUCCESS = 'GET_SELECTED_NOTE_SUCCESS';
export const GET_SELECTED_NOTE_FAIL = 'GET_SELECTED_NOTE_FAIL';
